# Generated by Django 3.2.4 on 2021-06-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='birth_date',
            field=models.IntegerField(null=True, verbose_name='birth_date'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='name',
            field=models.CharField(max_length=6, verbose_name='name'),
        ),
    ]
