# Generated by Django 3.2.4 on 2021-06-21 06:28

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210618_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books', validators=[books.validators.image_dimension_validator]),
        ),
    ]
