# Generated by Django 3.2.4 on 2021-06-24 05:18

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookmodel_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('cover', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
