# Generated by Django 3.2.4 on 2021-06-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('books', '0005_bookmodel_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='authors.authormodel'),
        ),
        migrations.DeleteModel(
            name='AuthorModel',
        ),
    ]
