# Generated by Django 3.2.4 on 2021-06-26 10:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20210626_1558'),
        ('books', '0006_auto_20210624_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='summary_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='summary_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='summary_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='genremodel',
            name='title_en',
            field=models.CharField(max_length=20, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='genremodel',
            name='title_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='genremodel',
            name='title_uz',
            field=models.CharField(max_length=20, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='authors.authormodel', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='books.GenreModel', verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='page_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='page_count'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='genremodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='genremodel',
            name='title',
            field=models.CharField(max_length=20, verbose_name='title'),
        ),
    ]
